import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#061946',
    marginBottom: 0,
    paddingTop: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingBottom: 0,
  },
  wrapper: {
    flexGrow: 1,
    alignItems: 'center',
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  tabs: {
    backgroundColor: '#0f4575',
    borderRadius: 50,
    overflow: 'hidden',
    paddingHorizontal: 0,
    marginHorizontal: 20,
  },
  tab: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 50,
    backgroundColor: 'transparent',
  },
  tabActive: {
    backgroundColor: '#24abdf',
    borderRadius: 50,
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  tabText: {
    fontFamily: 'Nunito-Bold',
    fontSize: 15,
    color: 'white',
  },
  tabUnderline: {
    height: 0,
  },
  avatar: {
    borderColor: '#24abdf',
    borderWidth: 3,
    width: 138,
    height: 138,
    borderRadius: 69,
    marginBottom: 28,
    backgroundColor: '#0f4575',
  },
  grid: {
    flex: 1,
    width: '100%',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    paddingHorizontal: 10,
    marginBottom: 20,
  },
  row: {
    flex: 1,
    width: '100%',
    marginBottom: 16,
  },
  withCol: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  withColCell: {
    paddingLeft: 16,
    marginLeft: 32,
    borderLeftColor: 'white',
    borderLeftWidth: 2,
  },
  label: {
    fontFamily: 'Nunito',
    fontSize: 16,
    fontWeight: 'normal',
    color: '#f3c744',
    letterSpacing: 0.16,
    marginBottom: 4,
  },
  text: {
    fontFamily: 'Nunito',
    fontSize: 20,
    fontWeight: '600',
    color: 'white',
    letterSpacing: 0.2,
  },
  button: {
    backgroundColor: '#0f4575',
  },
  input: {
    overflow: 'hidden',
    marginBottom: 16,
    paddingVertical: 0,
    paddingHorizontal: 8,
  },
  editButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  editButtonText: {
    fontFamily: 'Nunito',
    color: '#e94044',
    marginLeft: 8,
  },
  progressBarWrapper: {
    width: '100%',
    backgroundColor: 'white',
    height: 12,
    borderRadius: 6,
    overflow: 'hidden',
    marginBottom: 8,
  },
  topSection: {
    paddingHorizontal: 20,
    width: '100%',
    backgroundColor: '#061946',
    paddingTop: 20,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    marginBottom: 20,
  },
  progressBar: {
    height: 12,
    borderRadius: 6,
    backgroundColor: '#ffbb03',
    minWidth: '1%',
    maxWidth: '100%',
  },
   inputText: {
    color: '#FFF',
    fontSize: 15,
    fontFamily: 'Nunito-SemiBold',
  },
});
